Добавил тесты
Perevotortov/Sprint_3 pull request #1
Opened 2023-07-30 11:07 UTC by Perevotortov

Привет! Отправил задание на проверку.
    В пул реквесте папка tests с файлами:
1) test_constructor_sections - тесты на разделы конструктора
2) test_exit_from_cabinet - тест на логин и разлогин из личного кабинета
3) test_login_page - тесты на авторизацию. Я проверяю что переход по всем вариациям входа в аккаунт приводит на страницу авторизации, а затем проверяю саму авторизацию через фикстуру.
4) test_registration_page - тест на регистрацию и тест на появление ошибки ввода пароля. Фикстура для теста mymail
5) test_transition_from_lk_to_main_page - тесты перехода на главную страницу (раздел "Конструктор")
6) test_transition_from_main_page_to_lk - тесты перехода в личный кабинет
    В файле gitignore вписал:
/.idea/
/venv/
tests/__pycache__/
/.pytest_cache/
    Файл requirements содержит 2 строчки: 
﻿pytest==7.3.1
selenium==4.9.0
    Старался использовать локаторы по XPATH-у, чтобы не было путанницы. Поэтому не стал комментировать в readme все локаторы для тестов, если критично важно - переделаю, закомменчу.
    В каждом тесте внизу оставил комментарий с описанием работы.

2023-08-01 13:58 UTC, kadirovgm requested changes

2023-08-01 13:58 UTC, kadirovgm commented on conftest.py
> +def driver():
супер!

2023-08-01 13:58 UTC, kadirovgm commented on conftest.py
> +def mymail():
нужно исправить: по факту это сложно назвать фикстурой, скорее хелпер, такие методы обычно помещает либо к методам страницы (POM - узнаешь в 4 спринте), либо просто хранят в файле helper.py 

но это никак не фикстура, которая должна выполняться перед каждым тестовым методом и подготавливать данные

2023-08-01 13:58 UTC, kadirovgm commented on conftest.py
> +    wait.until(EC.presence_of_element_located((By.XPATH, "//button[contains(text(),'Войти в аккаунт')]"))).click()
можно лучше: все локаторы нужно  держать в одном месте, чтобы была единая точка входа, вот так наприяму в коде обращаться - плохая практика

2023-08-01 13:58 UTC, kadirovgm commented on conftest.py
> +    email = 'kirillprovotorov@mail.ru'
Можно лучше: тестовые статичные данные лучше выносить в отдельный файл типа [data.py](http://data.py/) или [urls.py](http://urls.py/)
Это нужно для легкой поддержке проекта и переиспользовании тестовых данных, мы должны стремиться к тому, чтобы разделять код и тестовые данные, тем самым избегая повторений.

2023-08-01 13:58 UTC, kadirovgm commented on tests/test_constructor_sections.py
> +        driver.find_element(By.XPATH, "//span[contains(text(),'Начинки')]").click()
нужно исправить: давай все таки вынесем все локаторы в отдельный файл locators.py и поместим их в классы по страницам, например MainPageLocators итп

2023-08-01 13:58 UTC, kadirovgm commented on tests/test_exit_from_cabinet.py
> +        assert driver.current_url == "https://stellarburgers.nomoreparties.site/login"
нужно исправить: кажется этот тест не совсем проверяет, что логаут корректный, скорее тест упадет на строке выше, при проверке наличия кнопки "Войти" после логаута - может его и стоит добавить в ассерт? иначе проверка наличия УРЛа /login не совсем отвечает на вопрос проищошел ли логаут

2023-08-01 13:58 UTC, kadirovgm commented on tests/test_login_page.py
> +        assert driver.current_url == "https://stellarburgers.nomoreparties.site/login"
можно лучше: проверка того, что URL поменялся на <url> не гарантирует, что страница прогрузилась, поэтому стоит ориентироваться на какие-либо элементы страницы, чекать, что они появились и отображаются корректно

2023-08-01 13:58 UTC, kadirovgm commented on tests/test_registration_page.py
> +        wait.until(EC.presence_of_element_located((By.XPATH, "//button[contains(text(),'Войти')]")))
нужно исправить: так как строки авторизации повторяются в нескольких тестх давай их поместим в отдельную функцию и будем только его вызывать, по аналогии с login

2023-08-01 13:58 UTC, kadirovgm commented on tests/test_registration_page.py
> +        assert error_message.is_displayed()
можно лучше: можно еще проверить корректность текста ошибки

2023-08-01 13:58 UTC, kadirovgm commented on tests/test_transition_from_lk_to_main_page.py
> +        driver.find_element(By.XPATH, "//header/nav[1]/div[1]/a[1]/*[1]").click()
нужно исправить: плохой локатор, не кажется стабильным, давай оптимизируем, не стоит завязываться на таких вложенностях

напоминаю, что локаторы должны быть стабильными, оптимальными, лаконичными, читабельными и короткими - учти это и пройдись по всем своим локаторам

2023-08-02 09:57 UTC, Perevotortov commented
Привет!
Проделал работу над ошибками, а именно:
1) "нужно исправить: по факту это сложно назвать фикстурой, скорее хелпер" , убрал фикстуру сделал файл хелпер, в него поместил функцию генерации почты, переименовал mymail -> get_mail, использовал в тестах ее вместе фикстуры.
2) "нужно исправить: давай все таки вынесем все локаторы в отдельный файл locators.py", не уверен в том, насколько я правильно понял как составлять файл с локаторами, но руководствовался информацией из интернета (в темах спринта не видел) и вроде составил рабочий вариант файла с локаторами.  Локаторы из файла использовал в тестах, рассортировал по страницам. Закомментил локаторы которые не очевидны по пути/названию.
3) "нужно исправить: кажется этот тест не совсем проверяет, что логаут корректный, скорее тест упадет на строке выше, при проверке наличия кнопки "Войти" после логаута - может его и стоит добавить в ассерт?" , исправил в тесте на логаут проверку, теперь это "assert wait.until(EC.presence_of_element_located((LoginPage.ENTER_BUTTON))).is_displayed()" с ожиданием элемента, и проверкой его отображения.
4) "нужно исправить: так как строки авторизации повторяются в нескольких тестх давай их поместим в отдельную функцию и будем только его вызывать, по аналогии с login", сделал фикстуру registration, использовал ее в тестах.
5) "нужно исправить: плохой локатор, не кажется стабильным, давай оптимизируем, не стоит завязываться на таких вложенностях", исправил и пересмотрел все локаторы, сократил все как смог.

6) Твой комментарий в тренажере: "..  добавь readme.md - туда лучше добавить описание проекта, использованные библиотеки и зависимости, описание тестов в разметке markdown ..." , Случайно добавил файл readme.md в ветке main при первом создании репозитория спринт_3, добавил в него пару строк чтобы он отобразился в ветке develop.
 
К сожалению, немного завис и пришлось делать в два коммита переделку- first rework/2. 
Буду ждать фидбек, спасибо!

2023-08-04 21:33 UTC, kadirovgm commented
На будущее, ты можешь оставлять свои комменты прям под моими комментами :)

2023-08-04 21:34 UTC, kadirovgm commented
спасибо за подробное объеснение изменени! супер)

2023-08-04 21:37 UTC, kadirovgm approved these changes

2023-08-04 21:37 UTC, kadirovgm commented on README.md
> +## Структура проекта
отлично! спасибо

2023-08-04 21:37 UTC, kadirovgm commented on conftest.py
> +def registration(driver):
супер!

2023-08-04 21:37 UTC, kadirovgm commented on locators.py
> +class CabinetPage:
можно лучше: PEP8 - между классами/методами оставляем пустую строку

2023-08-04 21:37 UTC, kadirovgm commented on locators.py
> +
отлично! теперь хорошие локаторы! 
Мы разделяем локаторы по страницам, согласно концепции POM все локаторы и все методы страницы должны лежать в одном месте

2023-08-07 12:11 UTC, merged